### ISSUE TITLE
timeout 2h

### ISSUE THREAD

**Issue by dopaemon** [projects-nexus/cirrus-script#1]
can build A12 With 2h ?????????

**Comment by ImSpiDy** [comment]
In 4-5 hours

**Comment by ImSpiDy** [comment]
@dopaemon I have uploaded readme 
You can check how this script works

**Comment by ImSpiDy** [comment]
@dopaemon I have updated the readme 
You can check how this script works

**Comment by ImSpiDy** [comment]
@dopaemon Sorry bro but drive isn't working for now 😅

**Comment by dopaemon** [comment]
> 
can you give me Dockerfile ?

**Comment by wHo-EM-i** [comment]
@dopaemon That docker image isn't created by us, you can use any docker just make sure rclone shouldn't be pre-installed in it since cirrus blocked it. You can simply use this docker "aarunalr/aosp-build"

**Comment by dopaemon** [comment]
> @dopaemon That docker image isn't created by us, you can use any docker just make sure rclone shouldn't be pre-installed in it since cirrus blocked it. You can simply use this docker "aarunalr/aosp-build"

oh. thks. i will try make symlink rclone

**Comment by dopaemon** [comment]
> @dopaemon That docker image isn't created by us, you can use any docker just make sure rclone shouldn't be pre-installed in it since cirrus blocked it. You can simply use this docker "aarunalr/aosp-build"

Hey bro. rclone work. check my repo

**Comment by wHo-EM-i** [comment]
@dopaemon dont know for me cirrus was not starting when i use any docker which has rclone, or even i try to install it with "apt install rclone" they just never start only a msg appera aosp building only allow for rom-builders org

**Comment by dopaemon** [comment]
> @dopaemon dont know for me cirrus was not starting when i use any docker which has rclone, or even i try to install it with "apt install rclone" they just never start only a msg appera aosp building only allow for rom-builders org

check my repo. :)) will work bro

**Comment by dopaemon** [comment]
> @dopaemon i don't need rclone anymore

ah okay ^^
