### ISSUE TITLE
How Can We Set The Bulid Type??

### ISSUE THREAD

**Issue by JaswantTeja** [projects-nexus/cirrus-script#2]
In This Repo There Is No Proper Guide to set the Bulid Type Like Buliding System Or Vendor Or Full Rom!!

Also I We Are Getting Timed Out When Is Rom Is At 70-75% By This We Can't Upload The Ccache.
Then How Can We Get The Ccache??

Also Give Support For Transfer.sh & So Users Can Get The Link By That They Can Mirror.

Thank You

**Comment by wHo-EM-i** [comment]
@JaswantTeja You don't have to set anything, just do youre bringup, like edit sync & build.sh and push, this script is fully automated you don't have to setup anything. It'll automatically start vendor+system with a timeout to get some time for uploading ccache. And automatically trigger next build of S or R depends on last build targets of system

**Comment by wHo-EM-i** [comment]
@JaswantTeja And about transfer.sh, we can't make it automated like we do with gindex cuz of random url, plus huge diff in spedd 10-15mbps vs +200mbps

**Comment by JaswantTeja** [comment]
> @JaswantTeja And about transfer.sh, we can't make it automated like we do with gindex cuz of random url, plus huge diff in spedd 10-15mbps vs +200mbps

okay Then Nice,Shall I Use My Index or Shall I Continue with The Default Index??

**Comment by wHo-EM-i** [comment]
@JaswantTeja You can't set-up your index its hard-coded

**Comment by JaswantTeja** [comment]
> @JaswantTeja You can't set-up your index its hard-coded

Oh Okay Tq 👍

**Comment by wHo-EM-i** [comment]
@JaswantTeja what do you mean by repo path

**Comment by JaswantTeja** [comment]
> @JaswantTeja what do you mean by repo path

When We Are Try To Sync There We Can See The Error To Update The Path 2.21 Something

**Comment by Prashant-1695** [comment]
@JaswantTeja Nothing

**Comment by Prashant-1695** [comment]
@JaswantTeja That's warning, try to see difference b/w error and warning

**Comment by JaswantTeja** [comment]
> @JaswantTeja Nothing

Okay Bro Running My 1st Bulid 👍

**Comment by wHo-EM-i** [comment]
@JaswantTeja ignore it, its just warning not error

**Comment by Prashant-1695** [comment]
@JaswantTeja 👍👍

**Comment by JaswantTeja** [comment]
> @JaswantTeja 👍👍

https://cirrus-ci.com/task/6044054214410240
Can You Please Check This And Tell Me
What is Happening.
I Got The Ccache of 4.6 GB and Uploaded Too but can't Get The Bulid. also it was saying Instance Rescheduled

**Comment by Prashant-1695** [comment]
@JaswantTeja Restart build again from cirrus

**Comment by wHo-EM-i** [comment]
@JaswantTeja Its random issue, cirrus side so we can't do anything. Just restart it, when it happens again
