### ISSUE TITLE
Where To Set The Bulid Type??

### ISSUE THREAD

**Issue by JaswantTeja** [projects-nexus/cirrus-script#3]
Like Where I Have To Define The Bulid For Gapps??

**Comment by wHo-EM-i** [comment]
@JaswantTeja You can do it in you're build.sh, also make sure to put R letter at the end of your commit massage to directly start full rom build instead of V/S type build which are used for ccache collection

**Comment by JaswantTeja** [comment]
> @JaswantTeja You can do it in you're build.sh, also make sure to put R letter at the end of your commit massage to directly start full rom build instead of V/S type build which are used for ccache collection

I Tried That But I'm Not Getting The Gapps Bulid

I Used "export WITH_GAPPS=true" In Bulid.sh

**Comment by Prashant-1695** [comment]
@JaswantTeja export not working rn, add flags in your dt
