### ISSUE TITLE
Upload CCACHE only on successful build of (vendor/system).img

### ISSUE THREAD

**Issue by wanderlusttt2** [projects-nexus/cirrus-script#4]
Can you make the script to upload the CCACHE only on successful build of vendor / system image as it uploads the cache unconditionally even if the build fails in between.

Maybe, a check similar to this could be used [here](https://github.com/projects-nexus/cirrus-script/blob/b9d2a430e065fdd27dec5b3ebdfae7faf9eaab0e/upload_ccache#L12-L13)

`
if [ ! -e out/target/product/*/(vendor/system).img ]; then
echo "• Uploading Cache On Gdrive •"
upload_ccache ccache.tar.gz
tg "$rom_name ccache was uploaded successfully!
Total Size: $(ls -sh ${PWD}/ccache.tar.gz | cut -d - -f 1 | cut -d / -f 1)
Time Took: $(($SECONDS / 60)) minute(s) and $(($SECONDS % 60)) second(s).
Status: $progress"
fi
`

**Comment by ImSpiDy** [comment]
But system img can't be compiled in one build

**Comment by orkunergun** [comment]
@wanderlusttt2 lol
