### ISSUE TITLE
Add support to push the CCACHE to github releases

### ISSUE THREAD

**Issue by wanderlusttt2** [projects-nexus/cirrus-script#5]
Add support to push the CCACHE to github releases on completion (or on failure) of Vendor / System / ROM Package, as the ccache saved gdrive index gets overriden everytime. It is better to use github releases as it will reduce the dependency on the gdrive index. Moreover, every user can have their own CCACHE for their builds.

**Comment by ImSpiDy** [comment]
@wanderlusttt2 download speed from github release is too slow

**Comment by wanderlusttt2** [comment]
> @wanderlusttt2 download speed from github release is too slow

Acha. got it

**Comment by wanderlusttt2** [comment]
> @wanderlusttt2 It will take around 20-30 mins to download 5 GB cache and whats wrong in overwritten cache?

Nothing wrong in it. But every user will have their own CCACHE instead of depending on the common CCACHE for a device.

**Comment by wanderlusttt2** [comment]
Dont think of me as "Issue Spammer". But i just thought it could be improved.

**Comment by ImSpiDy** [comment]
@wanderlusttt2 We made a common drive so that people can share cache

**Comment by ImSpiDy** [comment]
@wanderlusttt2 Why don't you join TG group lol
