### ISSUE TITLE
Fix Wen SpiDy Sir

### ISSUE THREAD

**Issue by reaPeR1010** [projects-nexus/cirrus-script#6]
Wen Fix

**Comment by akirasup3r** [comment]
@reaPeR1010 Never

**Comment by reaPeR1010** [comment]
@akirasup3r Damn tht hurt bro

**Comment by akirasup3r** [comment]
@reaPeR1010 Gm

**Comment by ImSpiDy** [comment]
@reaPeR1010 Fix yourself sar your are my master

**Comment by orkunergun68** [comment]
@reaPeR1010 lmao fix urself wen

**Comment by reaPeR1010** [comment]
@akirasup3r It's night now
So Good night
Tell gm tmrw

**Comment by ImSpiDy** [comment]
@reaPeR1010 You taught me everything

**Comment by akirasup3r** [comment]
@reaPeR1010 Ok bc

**Comment by akirasup3r** [comment]
@ImSpiDy Randi rona

**Comment by ImSpiDy** [comment]
@akirasup3r As expected from RTR

**Comment by akirasup3r** [comment]
@ImSpiDy +++++

**Comment by orkunergun68** [comment]
@shubhamxdd lol 🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣

**Comment by shubhamxdd** [comment]
@orkunergun68 wen fix bro i cant spam same rom builds 10 times

**Comment by reaPeR1010** [comment]
I'm tired bro
You guys won't help me
So I'm leaving

**Comment by shubhamxdd** [comment]
@reaPeR1010 acha chutad randi

**Comment by akirasup3r** [comment]
@reaPeR1010 JNL

**Comment by orkunergun68** [comment]
@reaPeR1010 Fix urself or delete ur GitHub account

**Comment by orkunergun68** [comment]
@shubhamxdd 😭😭😭😭😭
